### PR TITLE
Fix long decimals on angles

### PR DESCRIPTION
**Pull request by baptisteArno**
Fix issue when for example you want to round `M293,82 L313,82 L313,291 L288,291 L288,311`, it gives you long decimals for angles `M293,82L303,82A9.999999999999998,9.999999999999998,90,0,1,313,92L313,278.5A12.500000000000004,12.500000000000004,-270,0,1,300.5,291L298,291A9.999999999999998,9.999999999999998,-90,0,0,288,301L288,311`

### CODE REVIEW

**Comment by BrunoFenzl** [comment]
Hi @baptisteArno ! thanks for the proposed PR. Have you tried passing a value for the round parameter?
`roundCommands(commandsArray, radius, round)` The third parameter is the amount of decimal cases you want to have for  your coordinates, so it will round the value to that length.

**Comment by baptisteArno** [comment]
It won't round the angles though!

**Comment by BrunoFenzl** [comment]
Hi @baptisteArno, you got me in the middle of my vacations. I will take a look into it once I'm back.

**Comment by baptisteArno** [comment]
No worries 🙌

**Pull request merged**
